# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25d69319f1cb34aff59d70b5e05ea319be9dfcfe8262787c2787da00dd477fd59ca275875ad61bacc889edbf5990de5ec66f6a843d6cbca861a13905675dd058

test:
  secret_key_base: a191e9a73b9387e6381a9a649aed7fa9cd81651dd8afec5bd2bd00f12d7d5acadd3a5f98586356e894774a58dd08e3b7d5885fda0df82885283f1e335363fb53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
